### PR TITLE
$40 installer incentive

### PR DESCRIPTION
**Pull request by JamesVorder**

### CODE REVIEW

**Review by stephen304 — APPROVED** [review]

**Comment by cure** [comment]
A few suggestions to add to the criteria:
* The node owner needs to have the intention to leave the node up indefinitely, or at the very least through the end of the pilot phase (FIXME: what's the end date?)
* Node reachability will be checked automatically; the installation will become eligible for payment when the node reaches 95% uptime over 30 calendar days.

**Comment by JamesVorder** [comment]
Good catches Ward. I'll add both of those into the requirements. 

I think instead of tying the node's expected lifetime to the pilot -- which is getting longer every day as we run behind -- we could just say "The owner must agree to keep the node up for at least one year. Ideally, they would intend to keep it up permanently." @cure what do you think about that?

**Review by stephen304 — APPROVED** [review]

**Comment by cure** [comment]
@JamesVorder that sounds great thanks!

**Review by cure — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
